/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#1a1c1c',
        'tertiary-container': '#494a4a',
        'on-surface': '#1a1c1c',
        'surface-container-low': '#f3f3f3',
        'inverse-surface': '#2f3131',
        'primary-container': '#8e1b3b',
        'secondary': '#7b5455',
        'secondary-container': '#fecbcb',
        'outline-variant': '#debfc2',
        'tertiary': '#323434',
        'primary-fixed-dim': '#ffb2bc',
        'on-primary-fixed': '#400013',
        'surface-container-high': '#e8e8e8',
        'outline': '#8a7174',
        'surface-variant': '#e2e2e2',
        'on-tertiary-container': '#b9baba',
        'on-tertiary': '#ffffff',
        'surface-dim': '#dadada',
        'primary': '#6d0026',
        'secondary-fixed-dim': '#ecbaba',
        'on-error': '#ffffff',
        'surface': '#f9f9f9',
        'on-primary': '#ffffff',
        'background': '#f9f9f9',
        'on-secondary': '#ffffff',
        'on-background': '#1a1c1c',
        'error-container': '#ffdad6',
        'on-surface-variant': '#574144',
        'inverse-on-surface': '#f0f1f1',
        'inverse-primary': '#ffb2bc',
        'error': '#ba1a1a',
        'surface-container-highest': '#e2e2e2',
        'tertiary-fixed': '#e3e2e2',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#613d3e',
        'tertiary-fixed-dim': '#c6c6c6',
        'on-primary-container': '#ff9fad',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffd9dd',
        'on-tertiary-fixed-variant': '#464747',
        'on-secondary-fixed': '#2f1314',
        'on-secondary-container': '#7a5354',
        'surface-tint': '#aa314e',
        'surface-container': '#eeeeee',
        'on-primary-fixed-variant': '#891738',
        'surface-bright': '#f9f9f9',
        'secondary-fixed': '#ffdad9',
      },
      borderRadius: {
        DEFAULT: '0px',
        none: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        '3xl': '0px',
        full: '9999px',
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'serif'],
        body: ['"Manrope"', 'sans-serif'],
        label: ['"Manrope"', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
